# Generated by Django 5.1.4 on 2025-07-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halal', '0003_alter_brand_brand_name_alter_brand_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
