# Generated by Django 5.1.4 on 2025-07-16 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('halal', '0004_alter_brand_brand_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='check',
            name='description',
        ),
    ]
